---
name: Build GO & Docker push
    
on:
  workflow_dispatch:
  push:
    tags: 'v*'

env:
  REGISTRY: docker.io
  IMAGE_NAME: loic79/cowsay-go

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        sparse-checkout: |
          Dockerfile
          main.go
          go.sum

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

    - name: Build the cowsay
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.4'
        check-latest: true
    - run: go build -o bin/cowsay main.go

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

