---

    name: Build and Deliver The Cowsay app
    
    on:
        workflow_dispatch:
          inputs:

            version:
              description: "Version"   
              required: true
              default: 'v1.00'

            platform:
              type: choice
              description: Plateform
              options: 
              - amd64
              - arm64

            account:
              type: choice
              description: DockerHub account
              options: 
              - Loic
              - John

    
    env:
      REGISTRY: docker.io
      if: ${{ github.event.inputs.account == 'Loic' }}
      IMAGE_NAME: ${{ vars.DOCKERHUB_USERNAME }}/cowsay-go

    
    jobs:
#-----------------Build du main.go------------------------------                
      build:
        name: Build GO code in binary file

        runs-on: ubuntu-latest
        steps:

          - uses: actions/checkout@v4
    
          - uses: actions/setup-go@v5
            with:
              go-version: '>=1.23'
          
          - run: go version
    
          - run: go build -o bin/cowsay .
            env:
              GOARCH: ${{ github.event.inputs.platform }}
          
          - run: cp Dockerfile bin/
    
          - name: Upload static files as artifact
            id: deployment
            uses: actions/upload-artifact@v4
            with:
              path: bin/
              name: cowsaybin
      
#-----------------Déploiement sur une VM-------------------------                
      deploy:
        name: Deploy on Azure VM
        needs: build
        runs-on: ubuntu-latest
        steps:
          - uses: actions/download-artifact@v4
            with:
              path: .
              name: cowsaybin
          - run:  
               chmod u+x cowsay
              ./cowsay

#-----------------Déploiement sur DockerHub----------------------  
      push-docker:
        name: Push to DockerHub registery
        
        needs: build
        runs-on: ubuntu-latest
        steps:
          - uses: actions/download-artifact@v4
            with:
              path: .
              name: cowsaybin
    
          - run: chmod u+x cowsay
    
          - run: |
              pwd
              ls -alh
    
          - name: Docker meta
            id: meta
            uses: docker/metadata-action@v5
            with:
              images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
              tags: |
                type=raw, value=${{ github.event.inputs.version }}
            #  platforms: linux/${{ github.event.inputs.platform }}
    
          - name: Login to Docker Hub Loïc
            if: ${{ github.event.inputs.account == 'Loic' }}
            uses: docker/login-action@v3
            with:
              username: ${{ vars.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}

          - name: Set up QEMU
            uses: docker/setup-qemu-action@v3

          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3
    
          - name: Build and push
            uses: docker/build-push-action@v6
            with:
              context: .
              push: true
              tags: ${{ steps.meta.outputs.tags }}
              labels: ${{ steps.meta.outputs.labels }}
              platforms: linux/${{ github.event.inputs.platform }}